version: '3'

services:
  jenkins:
    image: 'jenkins/jenkins:2.60.3'
    ports:
      - '9090:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/var/jenkins_home'

volumes:
  jenkins_data:
    driver: local